# -*- coding: utf-8 -*-
"""RealPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1QwTn1fPDMBnC9vsDxqFvfCHf74DGDI
"""

from bs4 import BeautifulSoup

import requests

response=requests.get("https://realpython.com/")
#print(response.text)
print(type(response.text))

html_doc=response.text

soup=BeautifulSoup(html_doc,"html.parser")

titles=soup.find_all("h2")
titles

titles=soup.find_all("h2",class_="card-title")
titles

#x=[]
#for i in titles:
  #print(i.text)
  #x.append(i.text)
#x
x=[i.text for i in titles]
x

DIC={"CARD TITLES":x}
print(DIC)

import pandas as x
df=x.DataFrame(DIC)
df

df.index=range(1,len(df)+1)
df

df.to_csv("CARDTITLES.csv")